Task5
toadharvard/goxkcd pull request #10
Opened 2024-04-27 17:34 UTC by toadharvard

Добавлены ручки /update, /pics?limit=10&search="banana"&language=en

Протер архитектуру тряпочкой, стало еще чище.

2024-05-03 13:39 UTC, toadharvard commented
Нужно ревью
@maxan98 @vbelogrudov @kirreal

2024-05-06 07:26 UTC, vbelogrudov reviewed
впечатляет количество файлов в небольшом по функциональности проекте ;)

2024-05-06 08:10 UTC, vbelogrudov requested changes
привет!

если БД отсутствует, мы не получаем никаких ошибок, кроме логов. А когда ищем, то просто ничего не находим и возвращаем OK.

В идеале миграции должны накатываться или проверяться на каждый запуск сервера.

language должен быть по-умолчанию en.

update должен быть  POST

небольшая проблема в стеммере - 
http://localhost:8080/pics?search=apple,doctor&language=en ищет appledoctor

2024-05-06 08:10 UTC, vbelogrudov commented on internal/api/http/handlers.go
> +func PingHandler(ctx context.Context) http.HandlerFunc {
зачем здесь контекст?

2024-05-06 08:10 UTC, vbelogrudov commented on internal/api/http/api.go
> +	mux.HandleFunc("GET /ping", PingHandler(ctx))
если хочется использовать контекст в хендлерах, нужно создать недефолтный http.Server:

```
  server := http.Server{
    Addr:        ":8888",
    BaseContext: func(_ net.Listener) context.Context { return ctx },
  }
```

тогда в реквестах мы будем базироваться на нем, а не на context.Background(). 
```

// BaseContext optionally specifies a function that returns
	// the base context for incoming requests on this server.
	// The provided Listener is the specific Listener that's
	// about to start accepting requests.
	// If BaseContext is nil, the default is context.Background().
	// If non-nil, it must return a non-nil context.
	BaseContext func([net](https://pkg.go.dev/net).[Listener](https://pkg.go.dev/net#Listener)) [context](https://pkg.go.dev/context).[Context](https://pkg.go.dev/context#Context)
```

2024-05-06 08:10 UTC, vbelogrudov commented on internal/api/http/api.go
> +			app.DownloadComicsUseCase,
у нас в публичном API бизнеслогики по-хорошему нужны только Update и Search.

2024-05-06 08:14 UTC, vbelogrudov requested changes

2024-05-06 08:14 UTC, vbelogrudov commented on internal/repository/comix/postgres/repo.go
> +	query := SELECT(
возможно здесь получился перебор с ORM-like фреймворком :)

2024-05-06 15:23 UTC, toadharvard commented
> впечатляет количество файлов в небольшом по функциональности проекте ;)

Есть предложения, как уменьшить сцепление без разделения по модулям, как это сделано сейчас? Или какая проблема в количестве файлов, если назначение каждого очевидно (или нет)?

2024-05-06 15:29 UTC, toadharvard commented on internal/repository/comix/postgres/repo.go
> +	query := SELECT(
Это не ORM, а SQL-синтаксис со статической проверкой типов. Мне не нравится идея писать сырые строки для запросов или генерировать их c помощью sqlc. Потому что DSL >>> строка.

2024-05-06 15:59 UTC, toadharvard commented on internal/api/http/api.go
> +	mux.HandleFunc("GET /ping", PingHandler(ctx))
Это можно использовать, чтобы доставать контекст из r.Context.
Но я его из замыкания получаю. Есть какие-то причины предпочитать r.Context замыканию?

2024-05-06 16:04 UTC, toadharvard commented
> В идеале миграции должны накатываться или проверяться на каждый запуск сервера.

Это странно. Я считаю, что миграции должны накатываться независимо от старта сервера, потому что неконтролируемые миграции (те, которые запускает не программист руками) могут приводить к нарушению целостности базы данных.

Единственное место, где допустимо накатывать миграции автоматически -- тесты. Там же должны быть тесты с поочередной накаткой и откатом миграций.

2024-05-06 16:10 UTC, vbelogrudov commented on internal/api/http/api.go
> +	mux.HandleFunc("GET /ping", PingHandler(ctx))
Да. Клиент может контекст / запрос отменить

2024-05-06 16:10 UTC, vbelogrudov commented on internal/repository/comix/postgres/repo.go
> +	query := SELECT(
На sql это мало похоже, но тут спорить не буду

2024-05-06 16:27 UTC, vbelogrudov commented on internal/repository/comix/postgres/repo.go
> +	query := SELECT(
В данном случае больше проблема в когнитивной нагрузке, а не во фреймворке. Никто в моей команде не использовал jet с одной стороны (доп время на изучение фреймворка), с другой стороны любой сможет за 2 сек понять простой селект с простейшим where, в отличие от размашистого dsl. Это не запрос изменения, просто коммент 😀

2024-05-06 17:23 UTC, toadharvard commented on internal/api/http/api.go
> +			app.DownloadComicsUseCase,
Это если прямо дотошно следовать принципу "контроллеры должны быть тонкими", тут как будто без разницы)

2024-05-06 17:25 UTC, toadharvard commented
Вопросы выше все еще остались. А так исправлены все замечания, кроме API бизнеслогики (wontfix)

2024-05-06 17:54 UTC, vbelogrudov commented
> > В идеале миграции должны накатываться или проверяться на каждый запуск сервера.
> 
> Это странно. Я считаю, что миграции должны накатываться независимо от старта сервера, потому что неконтролируемые миграции (те, которые запускает не программист руками) могут приводить к нарушению целостности базы данных.
> 
> Единственное место, где допустимо накатывать миграции автоматически -- тесты. Там же должны быть тесты с поочередной накаткой и откатом миграций.

У нас вполне транзакционная миграция, если правильно писать и тестировать, - или все или ничего. И приложение привязано к конкретной версии схемы. Хуже, если приложение будет старым, а схема новой, или наоборот. Если само приложение контролирует схему, меньше зависимостей и ошибок в ручных миграциях и деплоях. В идеале все должно быть согласованно и идемпотентно.

2024-05-06 18:02 UTC, toadharvard commented
>  Хуже, если приложение будет старым, а схема новой, или наоборот

Это вполне возможно, если несколько инстансов приложения живет рядом (ну или в кубере) и накатывается новая версия. В единый момент времени может существовать две версии сервиса (не все инстансы успели обновиться).
И новая при старте применит миграции несовместимые со старой версией, что может вызвать эту самую деградацию.

А все потому что база данных -- разделяемый ресурс. Поэтому миграции предпочитаю накатывать независимо.

2024-05-06 18:03 UTC, vbelogrudov commented
Мы обычно перед выкатыванием новой версии делаем снепшот баз, поэтому даже если предположить, что мы недотестировали миграцию в дев-енве, выключился свет и т.п. у нас всегда есть возможность откатиться. А так апгрейд всегда тестируется перед выкатыванием в стейдже со свежим снепшотом актуальной базы, чтобы исключить несовместимость новых версий приложений со старыми базами. При очень сложной миграции, где изменения непросто залить в up скрипт, мы делаем это руками, есть для этого и скрипты и спец ручки в апи. Тут действительно надо отдельно и с тщательной проверкой.

2024-05-06 18:04 UTC, toadharvard commented
Да, это разумно

2024-05-07 07:34 UTC, vbelogrudov approved these changes

2024-05-07 07:39 UTC, vbelogrudov commented
По поводу размера кодовой базы, надо подумать. Получилось больше, чем ожидаем (в среднем 15-25 файлов на такой проект), может просто из-за кодогенерации + доп функциональнось. А так все отлично!

2024-05-10 13:45 UTC, merged